### PR TITLE
Sample app update

### PR DESCRIPTION
**Pull request by DavidKimVungle**
Temporarily put a working app ID until we can get something official in there like vungle_test. Added examples of event handlers.
Added dignostic messages for CS version.
Added more example for options.

### CODE REVIEW

**Comment by DavidKimVungle** [comment]
@sergeyksv Can you review the changes to public sample app and merge if everything looks good?

**Comment by sergeyksv** [comment]
@DavidKimVungle You didn't change appid in VB and DirectX sample. `https://github.com/Vungle/Windows-SDK/blob/sample-app-update/Windows%20Universal%20Samples/DirectX_XAML_sample/DirectXPage.xaml.cpp#L37` and `https://github.com/Vungle/Windows-SDK/blob/sample-app-update/Windows%20Universal%20Samples/VB_sample/MainPage.xaml.vb#L15`.

Besides that looks good for me.

**Comment by DavidKimVungle** [comment]
Hi Sergey,

I wasn't able to get to VB and DirectX and also I never had a support
request for those. I will get to them in the near future once I have more
bandwidth. I wanted to get a working build out with more examples for C#
and C++, which is used most by publishers.

Thanks,
David

**Comment by DavidKimVungle** [comment]
I have updated all test app ID to **Test_Windows**, including VB and DirectX sample.

**Pull request merged**
